- hosts: dev
  vars_files:
    - vars/default.yaml

  tasks:
    - name: Run code-server install script
      shell: curl -fsSL https://code-server.dev/install.sh | sh

    - name: Clone a git repository
      git:
        repo: https://github.com/agburov/Python.git
        dest: /home/khan/webeditor/
        clone: yes
        update: yes

    - name: Setup Python dependencies
      pip:
        requirements: /home/khan/webeditor/requirements.txt

    - name: Install useful extensions to the code server
      shell: "{{ web_editor_extensions }}"

    - name: Run code server without authentication in specific folder
      shell: code-server --auth none /home/khan/webeditor
